### ISSUE TITLE
Just FYI- error in the install

### ISSUE THREAD

**Issue by walinchus** [smach/rmiscutils#2]
I had to reinstall R(long story) and so I wanted this package again as it's super useful. But just FYI, I got some error messages in the install. I think it will still work for the things I want it to do, but I figured you'd want to know. Here is the entirety of the error: 

githubinstall:gh_install_packages("rmiscutils")
Suggestion:
 - smach/rmiscutils  This will be a collection of miscellaneous R functions I've written or found that have been useful over the years. I'm just starting to collect these.
Do you want to install the package (Y/n)?  y
Downloading GitHub repo smach/rmiscutils@master
These packages have more recent versions available.
Which would you like to update?

 1: All                                      
 2: CRAN packages only                       
 3: None                                     
 4: usethis     (1.5.0    -> 1.5.1   ) [CRAN]
 5: haven       (2.1.0    -> 2.2.0   ) [CRAN]
 6: curl        (4.0      -> 4.3     ) [CRAN]
 7: data.table  (1.12.2   -> 1.12.8  ) [CRAN]
 8: openxlsx    (4.1.0.1  -> 4.1.4   ) [CRAN]
 9: Rcpp        (1.0.2    -> 1.0.3   ) [CRAN]
10: hms         (0.4.2    -> 0.5.3   ) [CRAN]
11: R6          (2.4.0    -> 2.4.1   ) [CRAN]
12: clipr       (0.6.0    -> 0.7.0   ) [CRAN]
13: BH          (1.69.0-1 -> 1.72.0-3) [CRAN]
14: gh          (1.0.1    -> 1.1.0   ) [CRAN]
15: git2r       (0.25.2   -> 0.26.1  ) [CRAN]
16: purrr       (0.3.2    -> 0.3.3   ) [CRAN]
17: rlang       (0.4.0    -> 0.4.4   ) [CRAN]
18: whisker     (0.3-2    -> 0.4     ) [CRAN]
19: yaml        (2.2.0    -> 2.2.1   ) [CRAN]
20: tidyselect  (0.2.5    -> 1.0.0   ) [CRAN]
21: ellipsis    (0.2.0.1  -> 0.3.0   ) [CRAN]
22: pkgconfig   (2.0.2    -> 2.0.3   ) [CRAN]
23: vctrs       (0.2.0    -> 0.2.2   ) [CRAN]
24: cli         (1.1.0    -> 2.0.1   ) [CRAN]
25: fansi       (0.4.0    -> 0.4.1   ) [CRAN]
26: pillar      (1.4.2    -> 1.4.3   ) [CRAN]
27: digest      (0.6.21   -> 0.6.23  ) [CRAN]
28: prettyunits (1.0.2    -> 1.1.1   ) [CRAN]
29: zip         (2.0.2    -> 2.0.4   ) [CRAN]
30: stringi     (1.4.3    -> 1.4.5   ) [CRAN]
31: backports   (1.1.4    -> 1.1.5   ) [CRAN]
32: jsonlite    (1.6      -> 1.6.1   ) [CRAN]
33: mime        (0.7      -> 0.8     ) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
1
usethis     (1.5.0    -> 1.5.1   ) [CRAN]
haven       (2.1.0    -> 2.2.0   ) [CRAN]
curl        (4.0      -> 4.3     ) [CRAN]
data.table  (1.12.2   -> 1.12.8  ) [CRAN]
openxlsx    (4.1.0.1  -> 4.1.4   ) [CRAN]
Rcpp        (1.0.2    -> 1.0.3   ) [CRAN]
hms         (0.4.2    -> 0.5.3   ) [CRAN]
R6          (2.4.0    -> 2.4.1   ) [CRAN]
clipr       (0.6.0    -> 0.7.0   ) [CRAN]
BH          (1.69.0-1 -> 1.72.0-3) [CRAN]
gh          (1.0.1    -> 1.1.0   ) [CRAN]
git2r       (0.25.2   -> 0.26.1  ) [CRAN]
purrr       (0.3.2    -> 0.3.3   ) [CRAN]
rlang       (0.4.0    -> 0.4.4   ) [CRAN]
whisker     (0.3-2    -> 0.4     ) [CRAN]
yaml        (2.2.0    -> 2.2.1   ) [CRAN]
tidyselect  (0.2.5    -> 1.0.0   ) [CRAN]
ellipsis    (0.2.0.1  -> 0.3.0   ) [CRAN]
pkgconfig   (2.0.2    -> 2.0.3   ) [CRAN]
vctrs       (0.2.0    -> 0.2.2   ) [CRAN]
cli         (1.1.0    -> 2.0.1   ) [CRAN]
fansi       (0.4.0    -> 0.4.1   ) [CRAN]
pillar      (1.4.2    -> 1.4.3   ) [CRAN]
digest      (0.6.21   -> 0.6.23  ) [CRAN]
prettyunits (1.0.2    -> 1.1.1   ) [CRAN]
zip         (2.0.2    -> 2.0.4   ) [CRAN]
stringi     (1.4.3    -> 1.4.5   ) [CRAN]
backports   (1.1.4    -> 1.1.5   ) [CRAN]
jsonlite    (1.6      -> 1.6.1   ) [CRAN]
mime        (0.7      -> 0.8     ) [CRAN]
Installing 30 packages: usethis, haven, curl, data.table, openxlsx, Rcpp, hms, R6, clipr, BH, gh, git2r, purrr, rlang, whisker, yaml, tidyselect, ellipsis, pkgconfig, vctrs, cli, fansi, pillar, digest, prettyunits, zip, stringi, backports, jsonlite, mime

  There is a binary version available but the source version is later:
         binary source needs_compilation
jsonlite    1.6  1.6.1              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) Yes
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/usethis_1.5.1.tgz'
Content type 'application/x-gzip' length 912856 bytes (891 KB)
==================================================
downloaded 891 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/haven_2.2.0.tgz'
Content type 'application/x-gzip' length 1077133 bytes (1.0 MB)
==================================================
downloaded 1.0 MB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/curl_4.3.tgz'
Content type 'application/x-gzip' length 741337 bytes (723 KB)
==================================================
downloaded 723 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/data.table_1.12.8.tgz'
Content type 'application/x-gzip' length 2133679 bytes (2.0 MB)
==================================================
downloaded 2.0 MB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/openxlsx_4.1.4.tgz'
Content type 'application/x-gzip' length 2949701 bytes (2.8 MB)
==================================================
downloaded 2.8 MB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/Rcpp_1.0.3.tgz'
Content type 'application/x-gzip' length 3099696 bytes (3.0 MB)
==================================================
downloaded 3.0 MB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/hms_0.5.3.tgz'
Content type 'application/x-gzip' length 103612 bytes (101 KB)
==================================================
downloaded 101 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/R6_2.4.1.tgz'
Content type 'application/x-gzip' length 57479 bytes (56 KB)
==================================================
downloaded 56 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/clipr_0.7.0.tgz'
Content type 'application/x-gzip' length 48251 bytes (47 KB)
==================================================
downloaded 47 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/BH_1.72.0-3.tgz'
Content type 'application/x-gzip' length 11253901 bytes (10.7 MB)
==================================================
downloaded 10.7 MB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/gh_1.1.0.tgz'
Content type 'application/x-gzip' length 109951 bytes (107 KB)
==================================================
downloaded 107 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/git2r_0.26.1.tgz'
Content type 'application/x-gzip' length 2062255 bytes (2.0 MB)
==================================================
downloaded 2.0 MB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/purrr_0.3.3.tgz'
Content type 'application/x-gzip' length 412501 bytes (402 KB)
==================================================
downloaded 402 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/rlang_0.4.4.tgz'
Content type 'application/x-gzip' length 1171655 bytes (1.1 MB)
==================================================
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/whisker_0.4.tgz'
Content type 'application/x-gzip' length 65424 bytes (63 KB)
==================================================
downloaded 63 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/yaml_2.2.1.tgz'
Content type 'application/x-gzip' length 204091 bytes (199 KB)
==================================================
downloaded 199 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/tidyselect_1.0.0.tgz'
Content type 'application/x-gzip' length 240162 bytes (234 KB)
==================================================
downloaded 234 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/ellipsis_0.3.0.tgz'
Content type 'application/x-gzip' length 33047 bytes (32 KB)
==================================================
downloaded 32 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/pkgconfig_2.0.3.tgz'
Content type 'application/x-gzip' length 17573 bytes (17 KB)
==================================================
downloaded 17 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/vctrs_0.2.2.tgz'
Content type 'application/x-gzip' length 992621 bytes (969 KB)
==================================================
downloaded 969 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/cli_2.0.1.tgz'
Content type 'application/x-gzip' length 386502 bytes (377 KB)
==================================================
downloaded 377 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/fansi_0.4.1.tgz'
Content type 'application/x-gzip' length 210779 bytes (205 KB)
==================================================
downloaded 205 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/pillar_1.4.3.tgz'
Content type 'application/x-gzip' length 178277 bytes (174 KB)
==================================================
downloaded 174 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/digest_0.6.23.tgz'
Content type 'application/x-gzip' length 247784 bytes (241 KB)
==================================================
downloaded 241 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/prettyunits_1.1.1.tgz'
Content type 'application/x-gzip' length 35656 bytes (34 KB)
==================================================
downloaded 34 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/zip_2.0.4.tgz'
Content type 'application/x-gzip' length 196402 bytes (191 KB)
==================================================
downloaded 191 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/stringi_1.4.5.tgz'
Content type 'application/x-gzip' length 13607372 bytes (13.0 MB)
==================================================
downloaded 13.0 MB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/backports_1.1.5.tgz'
Content type 'application/x-gzip' length 56012 bytes (54 KB)
==================================================
downloaded 54 KB

trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/mime_0.8.tgz'
Content type 'application/x-gzip' length 35364 bytes (34 KB)
==================================================
downloaded 34 KB

The downloaded binary packages are in
	/var/folders/y9/l7s4rm2x0g934jww243w_mxh0000gn/T//RtmpJUhTWw/downloaded_packages
installing the source package ‘jsonlite’

trying URL 'https://cran.rstudio.com/src/contrib/jsonlite_1.6.1.tar.gz'
Content type 'application/x-gzip' length 1057910 bytes (1.0 MB)
==================================================
downloaded 1.0 MB

* installing *source* package ‘jsonlite’ ...
** package ‘jsonlite’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Iyajl/api  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include   -fPIC  -Wall -g -O2  -c base64.c -o base64.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Iyajl/api  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include   -fPIC  -Wall -g -O2  -c collapse_array.c -o collapse_array.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Iyajl/api  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include   -fPIC  -Wall -g -O2  -c collapse_object.c -o collapse_object.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Iyajl/api  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include   -fPIC  -Wall -g -O2  -c collapse_pretty.c -o collapse_pretty.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Iyajl/api  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include   -fPIC  -Wall -g -O2  -c escape_chars.c -o escape_chars.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Iyajl/api  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include   -fPIC  -Wall -g -O2  -c integer64_to_na.c -o integer64_to_na.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Iyajl/api  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include   -fPIC  -Wall -g -O2  -c is_datelist.c -o is_datelist.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Iyajl/api  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include   -fPIC  -Wall -g -O2  -c is_recordlist.c -o is_recordlist.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Iyajl/api  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include   -fPIC  -Wall -g -O2  -c is_scalarlist.c -o is_scalarlist.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Iyajl/api  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include   -fPIC  -Wall -g -O2  -c modp_numtoa.c -o modp_numtoa.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Iyajl/api  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include   -fPIC  -Wall -g -O2  -c null_to_na.c -o null_to_na.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Iyajl/api  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include   -fPIC  -Wall -g -O2  -c num_to_char.c -o num_to_char.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Iyajl/api  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include   -fPIC  -Wall -g -O2  -c parse.c -o parse.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Iyajl/api  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include   -fPIC  -Wall -g -O2  -c prettify.c -o prettify.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Iyajl/api  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include   -fPIC  -Wall -g -O2  -c push_parser.c -o push_parser.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Iyajl/api  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include   -fPIC  -Wall -g -O2  -c r-base64.c -o r-base64.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Iyajl/api  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include   -fPIC  -Wall -g -O2  -c register.c -o register.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Iyajl/api  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include   -fPIC  -Wall -g -O2  -c row_collapse.c -o row_collapse.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Iyajl/api  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include   -fPIC  -Wall -g -O2  -c transpose_list.c -o transpose_list.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Iyajl/api  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include   -fPIC  -Wall -g -O2  -c validate.c -o validate.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Iyajl/api  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include   -fPIC  -Wall -g -O2  -c yajl/yajl.c -o yajl/yajl.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Iyajl/api  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include   -fPIC  -Wall -g -O2  -c yajl/yajl_alloc.c -o yajl/yajl_alloc.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Iyajl/api  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include   -fPIC  -Wall -g -O2  -c yajl/yajl_buf.c -o yajl/yajl_buf.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Iyajl/api  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include   -fPIC  -Wall -g -O2  -c yajl/yajl_encode.c -o yajl/yajl_encode.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Iyajl/api  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include   -fPIC  -Wall -g -O2  -c yajl/yajl_gen.c -o yajl/yajl_gen.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Iyajl/api  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include   -fPIC  -Wall -g -O2  -c yajl/yajl_lex.c -o yajl/yajl_lex.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Iyajl/api  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include   -fPIC  -Wall -g -O2  -c yajl/yajl_parser.c -o yajl/yajl_parser.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -Iyajl/api  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include   -fPIC  -Wall -g -O2  -c yajl/yajl_tree.c -o yajl/yajl_tree.o
ar rcs yajl/libstatyajl.a yajl/yajl.o yajl/yajl_alloc.o yajl/yajl_buf.o yajl/yajl_encode.o yajl/yajl_gen.o yajl/yajl_lex.o yajl/yajl_parser.o yajl/yajl_tree.o
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o jsonlite.so base64.o collapse_array.o collapse_object.o collapse_pretty.o escape_chars.o integer64_to_na.o is_datelist.o is_recordlist.o is_scalarlist.o modp_numtoa.o null_to_na.o num_to_char.o parse.o prettify.o push_parser.o r-base64.o register.o row_collapse.o transpose_list.o validate.o -Lyajl -lstatyajl -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-jsonlite/00new/jsonlite/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (jsonlite)

The downloaded source packages are in
	‘/private/var/folders/y9/l7s4rm2x0g934jww243w_mxh0000gn/T/RtmpJUhTWw/downloaded_packages’
✔  checking for file ‘/private/var/folders/y9/l7s4rm2x0g934jww243w_mxh0000gn/T/RtmpJUhTWw/remotese5d7324d0f7c/smach-rmiscutils-3fb06a8/DESCRIPTION’ ...
─  preparing ‘rmiscutils’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘rmiscutils_0.2.tar.gz’
   
* installing *source* package ‘rmiscutils’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Note: break used in wrong context: no loop is visible 
Note: break used in wrong context: no loop is visible 
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (rmiscutils)
**_Error in githubinstall:gh_install_packages("rmiscutils") : 
  NA/NaN argument
In addition: Warning messages:
1: In fread(download_url, sep = "\t", header = FALSE, stringsAsFactors = FALSE,  :
  Found and resolved improper quoting out-of-sample. First healed line 4848: <<Puriney	honfleuR	"Evening, honfleuR" by Seurat>>. If the fields are not quoted (e.g. field separator does not appear within any field), try quote="" to avoid this warning.
2: NAs introduced by coercion `_**

**Comment by walinchus** [comment]
Error just at the end there really.

**Comment by smach** [comment]
Thanks for letting me know! I'm not sure what that's all about. I'll try to re-install on my Windows and Mac systems and see if I get the same.

**Comment by smach** [comment]
Sorry for the delay in answering.  I didn't get that error when re-installing either on my Mac or my Windows PC. Looks like this has [happened elsewhere with other packages](https://github.com/gisma/uavRst/issues/12). Anyway thanks for taking the time to tell me.
